### PR TITLE
Allow blocks in templates

### PR DESCRIPTION
**Pull request by stephenafamo**

### CODE REVIEW

**Comment by joerdav** [comment]
Thanks for the contribution! Just wondering if you could give a quick example of the situation this fixes, just so I can verify it works as expected :)

**Comment by stephenafamo** [comment]
Using Go code in curly braces in breaks highlighting for the rest of the template.

Before:
image


After:
image

**Comment by joerdav** [comment]
Awesome, happy to merge, I probably would have fixed this now if I hadn't switched to https://github.com/vrischmann/tree-sitter-templ

**Comment by stephenafamo** [comment]
> Awesome, happy to merge, I probably would have fixed this now if I hadn't switched to https://github.com/vrischmann/tree-sitter-templ

Yeah. If I ever switch to neovim, I'll move over too 😁

**Review by skydiver1980 — APPROVED** [review]

**Pull request merged**
